version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: meetings-db
    environment:
      POSTGRES_DB: meetings
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 2s
      timeout: 2s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate:v4.16.2
    container_name: meetings-migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./internal/adapters/postgres/init:/migrations:ro
    command: [
      "-path", "/migrations",
      "-database", "postgres://user:pass@db:5432/meetings?sslmode=disable",
      "up"
    ]
    restart: "on-failure"

  app:
    image: meeting-svc:local
    container_name: meetings-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      CONFIG_PATH: /app/config/prod.yaml
      HTTP_SERVER_PASSWORD: "pass"
    ports:
      - "8081:8081"

volumes:
  pgdata:
